version: "3"
services:
    mongodb:
      image : "mongo"
      container_name: mongodb
      environment:
      - PUID=1000
      - PGID=1000
      volumes:
      - database-data:/var/lib/mongo_docker/data/
      ports:
      - 27017:27017
      restart: unless-stopped


volumes:
  database-data: